### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by JacquiM** [Demi147/Dimension-Data-Collab#1]
https://github.com/Demi147/Dimension-Data-Collab

line 33 - if there's no logic, remove the foreach

line 68, 83, 98, 113, 128 - if you're catching an exception, it's best to do something with it

**Comment by JacquiM** [comment]
Thanks for giving me the username and password to your DB containing employee data in your appsettings.json file :D

**Comment by Demi147** [comment]
Fixed data logic flaws: removed the exception. Removed unused method. 
Removed appsettings.json from commit history and changed DB password

**Comment by Demi147** [comment]
Fixed data logic: Removed unused method. Also removed exceptions from the catches (now just breaking the loop instead)
Removed appsettings.json from commit history and changed DB password.
